version: '3.8'
services:
  db:
    image: postgres:13-alpine3.18
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=helloworldpostgres
      - POSTGRES_DB=helloworld
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
  helloworld:
    image: docker.io/library/helloworld:latest
    environment:
      - DB_URL=jdbc:postgresql://db:5432/helloworld
      - DB_USERNAME=postgres
      - DB_PASSWORD=helloworldpostgres
    restart: always
    ports:
      - '8090:8080'
    depends_on:
      - db
volumes:
  db:
    driver: local