spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/helloworld}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:helloworldpostgres}
  flyway:
    locations: classpath:db/shared
    schemas: public
    enabled: true

  jpa:
    show-sql: false
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect