name: CI/CD Pipeline
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  GIT_USERNAME: rebla-rev
  APP_NAME: helloworld

jobs:
  build:
    runs-on: [ ubuntu-22.04 ]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'
          cache: maven

      - name: Maven build and test
        run: mvn --batch-mode --update-snapshots -P clean install

      - name: Login to docker registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ env.GIT_USERNAME }}
          password: ${{ secrets.PAT }}

      - name: Build and push Image
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          file: ./Dockerfile
          push: true
          tags: ghcr.io/${{ env.GIT_USERNAME }}/${{ env.APP_NAME }}:latest
